title: mobi3006 website
description: website based on Jeykll/GithubPages and the fantastic Just the Docs theme!
theme: just-the-docs

url: https://mobi3006.github.io/website/
#favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/pierreinside.jpg"

search_enabled: true
heading_anchors: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  github: https://github.com/mobi3006/website
  pierreinside: https://mobi3006.gitbooks.io/pierreinside
  JustTheDocs: https://github.com/just-the-docs/just-the-docs-template
aux_links_new_tab: rue